### ISSUE TITLE
Create overview page for a dataset

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#235]
coming from https://github.com/girder/viime/pull/217#issuecomment-532708162

create an overview page of a dataset showing
 * name
 * size
 * upload date
 * ??

related to #197 which could be done here, too

---
> +1 to the overview page. Let me know if you need some sort of design added to the mockups for that or the sidebar, or if you think you have a clear enough path you can build it and I can provide feedback once it's ready.

**Comment by subdavis** [comment]
This application has already embraced "saveless" ux in the cleanup, upload, and transform views, so it might be nice to follow that trend with the rename and description edit.

Rather than a dialog where you edit the name and description and hit save, could we have text that transform to inputs on click and autosave after some debouncing?

In addition to the things above, we can also show:

* maybe an overview of how many metaboloites and samples there are.
* Maybe a summary of the metadata and groups?  Perhaps we could show the groups enumerated in pills or something?
