### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#243]
I've made a rough [mockup](https://docs.google.com/drawings/d/1XFh0NTVz_ctDip2LA9C5jcvVIIieYPuh5rnoOCKbwH4/edit?usp=sharing). @jtomeck could you put this on your list to directly code up in Vue? This page would get the root route in the app, perhaps @subdavis could get you set up with an initial empty .vue file.

The following issues can be solved as part of this:
- #309 
- #310

**Comment by subdavis** [comment]
Neat.  Related to #241

I suppose we also need a mockup of what happens when you click the sample data button.  I imagine upload takes you to the upload page.  Perhaps sample data does the same thing, but with an 80% or 90% width dialog where you can browse the sample data. 

Maybe a 2-line v-list would be good here.  Title and description + a "lauch" or "use" button would probably be enough to get started.  Tiles may also be valid, but they may also just waste space.

**Comment by jtomeck** [comment]
@jeffbaumes - This sounds good Jeff. What's the urgency of this?

@subdavis if you could get me set up like Jeff mentioned that would be great.

**Comment by subdavis** [comment]
@jtomeck working on it :+1:

**Comment by jeffbaumes** [comment]
@jtomeck We need to have this up and have had a few feedback iterations done by Nov 15. So Oct 15 would be an adequate due date for the first pass.
