### ISSUE TITLE
API design for accessing imputed data

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#254]

**Comment by jbeezley** [comment]
Looking at the code, the post imputation (pre-transformation) table is returned as `.measurement_table` in the `GET /csv/:id` endpoint.  This is technically all the client needs to display this information to the user; however, determining the mapping to the source table is non-trivial due to masking/metadata.

I could use some guidance on what additional information would help the logic on the client.

* Would a flat list of imputed elements (equivalent to a list of NaN's in the source dataset) be helpful?
* If so, how should these elements be indexed?  By their index in the source table, the measurement table, or by header/primary key string?
* Would this list also contain the imputed value?
* Should we rethink how we are transmitting tables (related #208)?
* Should this be added to the main endpoint or sent with a new endpoint?  It may be another case of information always needed so it is burdensome to require another rest request.  OTOH, there may be performance issues on sending back a (potentially) long list of elements.

**Comment by waxlamp** [comment]
> Looking at the code, the post imputation (pre-transformation) table is returned as .measurement_table in the GET /csv/:id endpoint. This is technically all the client needs to display this information to the user; however, determining the mapping to the source table is non-trivial due to masking/metadata.

Currently, the client *doesn't* show imputed values, right? I think you're right, the mapping to the source data table is currently the showstopper.

> Would a flat list of imputed elements (equivalent to a list of NaN's in the source dataset) be helpful?

I think so, because in the current situation this would allow us to, at the very least, display the imputed data as though it had been there all along; and more importantly, will let us style the imputed values in some way (even if it's just displaying them with an asterisk, etc.).

> If so, how should these elements be indexed? By their index in the source table, the measurement table, or by header/primary key string?

I assume by index in the source table, or by header/primary key string, would be the most effective methods for enabling "imputed value display".

> Would this list also contain the imputed value?

That seems the most straightforward way to get started, though if the index in the list can be easily made to refer to the measurement table, then maybe that's more efficient. Either way, we would likely need a computed property of some kind to make it easier on the client to reference these values.

> Should we rethink how we are transmitting tables (related #208)?

Would the idea be to have "imputed table" alongside "validated table" as a model type? Or do you just mean restructuring the response from the CSV endpoint?

> Should this be added to the main endpoint or sent with a new endpoint? It may be another case of information always needed so it is burdensome to require another rest request. OTOH, there may be performance issues on sending back a (potentially) long list of elements.

I think it's probably fine to add it to the main endpoint, since in the usual case the number of imputed values should be an order of magnitude smaller than non-imputed data values.

**Comment by sgratzl** [comment]
partly covered in https://github.com/girder/viime/pull/304/files by adding the `missing_cells: [number, number][]` property to a dataset

**Comment by sgratzl** [comment]
can we close this issue?

**Comment by jeffbaumes** [comment]
Yes
