### ISSUE TITLE
Zooming in/out resizes the window but doesn't resize the plots itself

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#616]
via @jkanche

**Comment by mvandenburgh** [comment]
Just to add context to this since I also just ran into this problem - this seems to be specifically referring to the plots on the PCA analysis page. The Score Plot does properly zoom in/out, but the Scree and Loadings plots don't (see loadings plot below)

![pmFSBgvJmx](https://user-images.githubusercontent.com/37340715/89941796-8c8af000-dbe9-11ea-859c-3a899b8948c0.gif)

**Comment by waxlamp** [comment]
Should we just remove the zoom controls from the plots that don't use it?

We could add zooming semantics for the scree plot, but I am not sure what value that adds.

**Comment by waxlamp** [comment]
@jkanche, this turned out to be a bug, where most of our plots are not meant to resize in this way, and thus shouldn't have had resizing controls. Thanks for bringing this up!
