### ISSUE TITLE
Including example datasets in local installation

### ISSUE THREAD

**Issue by joannawolthuis** [girder/viime#622]
Hi crew! Thanks for the updated instructions :) I can properly load up the server now! I was wondering if examples are included in the local installation ? For me I am forever stuck here:
![image](https://user-images.githubusercontent.com/16805477/90006746-ca475180-dc99-11ea-93c1-53834e912d07.png)
So either I'd have a 'no examples available' prompt here, or include them (which would be nice for further testing)

**Comment by waxlamp** [comment]
Hi @joannawolthuis!

I investigated a bit, and for me I always see a panel that says "no datasets found"--*unless* the server is not running, in which case I see the situation you have described (I opened #625 to address this, putting up an error message instead of just forever spinning).

Can you confirm that your server is running? A `docker ps` command should show two containers named `docker_backend_1` and `docker_opencpu_1`. If you do have those running, we'll have to dig a bit deeper.

**Comment by jeffbaumes** [comment]
Regardless of if we can get this working, add a pointer to an example CSV that works with the system from the README.

**Comment by waxlamp** [comment]
Hi @joannawolthuis!

After merging #649, there are now sample datasets included in the repository, along with instructions on how to use them to set things up in a local build. Please let me know if this is working for you (reopen this issue if there are still problems). Thanks!
