### ISSUE TITLE
The term "selection" is overloaded

### ISSUE THREAD

**Issue by subdavis** [girder/viime#692]
"Selection" as a term is so overloaded that I think it's at risk of causing a lot of user confusion.  I see this as an opportunity to do some easy UI Improvement that might also count as a bit of marketing.

Copied from #691 

>In general, the UX around our global selected set is pretty confusing. One problem is that the term "selection" is way too overloaded in this app. We probably need a unique phrase to identify this ability to globally choose a group of metabolites across analyses. This could even tie into our marketing: we could use this phrase to identify the feature as a particular strength of the tool. Something like "Interest group". Or we could identify the repository almost like a shopping cart: "Add this metabolite to your magnifying glass?" These are objectively bad names, but you get the point.

**Comment by waxlamp** [comment]
If this UI is confusing to one of the core developers, then it definitely needs to be fixed (perhaps not immediately, but it needs some attention when we do work on this codebase full time).

One suggestion I have specifically for the "magnifying glass" feature: find out how Tom thinks about this operation. There is probably a term in biology or experimental science in general for selecting a set of subjects for running analyses on as a group. It's different from terms like "control group" and "experimental group" but probably related.

We might also consult Jared, since this type of global selection probably exists as a general concept in web apps (or other GUI apps) as well.

Final thought: if we support a comprehensive framework for creating "shopping carts" of metabolites, we could probably go one step further and allow for saving these subsets for retrieval later. I imagine this would be a matter of keeping these subsets in the store, and directing certain operations to work on that subset.

**Comment by jeffbaumes** [comment]
Let's bring this up in discussion at today's meeting. The "favorited/starred" and "in shopping cart" metaphors are two we could use, though I feel neither is a perfect match, and something like "of interest" would be more accurate. An icon with a count bubble, and a page/popover which lists what is currently in the "of interest" set could be nice.

**Comment by subdavis** [comment]
From today's meeting, it seems like this isn't something we need to do at this time. 

I'll close this issue for now.
